### ISSUE TITLE
`Tracking` and `Debugger`

### ISSUE THREAD

**Issue by seemir** [seemir/stressa#163]
**Bettering the tracking of exceptions**

- [x] Add a `Tracking` and `Debugger` decorator utility for keeping better track of `Exceptions`

- [x] Update test-suites given introduction of new decorators

- [x] Add `Tracking` and `Debugger` to necessary classes in `app` and `domain` layers

**Comment by seemir** [comment]
Closed by (ed0967f171641e7ce3737c7df18963f308e01049)
